services:
  api:
    build: .
    container_name: housing-property-price-prediction-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL = ${REDIS_URL}
      - BUCKET_NAME = ${BUCKET_NAME}
      - MODEL_PIPELINE_KEY = ${MODEL_PIPELINE_KEY}
    depends_on:
      - redis
      - prometheus

  redis:
    image: redis
    container_name: housing-property-price-prediction-redis
    ports:
      - "6379:6379"
    networks:
      - housing-property-price-prediction-network

  prometheus:
    image: prom/prometheus:latest
    container_name: housing-property-price-prediction-prometheus
    ports:
      - "9090:9090"
    networks:
      - housing-property-price-prediction-network

  grafana:
    image: grafana/grafana:latest
    container_name: housing-property-price-prediction-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - housing-property-price-prediction-network

networks:
  housing-property-price-prediction-network:
    driver: bridge
