columns:
  - amount: float
  - location: str
  - carpet_area: float
  - transaction: str
  - furnishing: str
  - facing: str
  - bathroom: float
  - balcony: float
  - ownership: str
  - super_area: float
  - num_bhk: float
  - floor_num: float
  - num_floors: float
  - overlooking_garden: float
  - overlooking_mainroad: float
  - overlooking_pool: float
  - parking_spots: float
  - parking_cover: str
